[package]
name = "schemantic"
version = "0.1.0"
edition = "2024"

[lib]
name = "schemantic"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }

[package.metadata.maturin]
name = "schemantic"
